const sm = ["SM-0", "SM-1"];

const yrSections = [
  "BSIT 1-1",
  "BSIT 1-2",
  "BSIT 2-1",
  "BSIT 2-2",
  "BSIT 3-1",
  "BSIT 3-2",
  "BSIT 4-1",
  "BSIT 4-2",
  "BSCpE 1-1",
  "BSCpE 1-2",
  "BSCpE 2-1",
  "BSCpE 2-2",
  "BSCpE 3-1",
  "BSCpE 3-2",
  "BSCpE 4-1",
  "BSCpE 4-2",
  "BSA 1-2",
  "BSA 2-1",
  "BSA 2-2",
  "BSA 3-1",
  "BSA 3-2",
  "BSA 4-1",
  "BSA 4-2",
  "BSHM 1-2",
  "BSHM 1-1",
  "BSHM 2-1",
  "BSHM 2-2",
  "BSHM 3-1",
  "BSHM 3-2",
  "BSHM 4-1",
  "BSHM 4-2",
  "BSENTREP 1-1",
  "BSENTREP 1-2",
  "BSENTREP 2-1",
  "BSENTREP 2-2",
  "BSENTREP 3-1",
  "BSENTREP 3-2",
  "BSENTREP 4-1",
  "BSENTREP 4-2",
  "BSENTREP 1-1",
  "BSEd Eng 1-2",
  "BSEd Eng 2-1",
  "BSEd Eng 2-2",
  "BSEd Eng 3-1",
  "BSEd Eng 3-2",
  "BSEd Eng 4-1",
  "BSEd Eng 4-2",
  "BSEd Math 1-2",
  "BSEd Math 2-1",
  "BSEd Math 2-2",
  "BSEd Math 3-1",
  "BSEd Math 3-2",
  "BSEd Math 4-1",
  "BSEd Math 4-2",
  "DOMT 1-2",
  "DOMT 2-1",
  "DOMT 2-2",
  "DOMT 3-1",
  "DOMT 3-2",
];
const yrSN = [
  "2005",
  "2006",
  "2007",
  "2008",
  "2009",
  "2010",
  "2011",
  "2012",
  "2013",
  "2014",
  "2015",
  "2016",
  "2017",
  "2018",
  "2019",
  "2020",
  "2021",
  "2022",
  "2023",
  "2024",
  "2025",
  "2026",
  "2027",
  "2028",
  "2029",
  "2030",
];

const transactionsAcad = [
  "Processing of Application for Overload of Subjects",
  "Processing of Application for Change of Enrollment (Adding of Subject)",
  "Processing of Application for Change of Enrollment (Change of Schedule/Subject)",
  "Processing of Application for Correction of Grade Entry, Late Reporting of Grades and Removal of Incomplete Mark",
  "Processing of Application for Cross-Enrollment",
  "Processing of Application for Shifting",
  "Processing of Manual Enrollment ",
  "Processing of Online Petition of Subject",
  "Processing of Online Request for Tutorial of Subject",
  "Processing of Request for Certification (Grades, Bonafide Student, General Weighted Average)",
];

const transactionsReg = [
  "ISSUANCE OF CERTIFIED TRUE COPY OF REGISTRATION CARD",
  "ISSUANCE OF Duplicate Copy of Registration card",
  "ISSUANCE OF CERTIFICATE OF ENROLLMENT",
  "ISSUANCE OF PERMIT TO CROSS ENROLL COURSE",
  "ISSUANCE OF CERTIFICATION, AUTHENTICATION AND VERIFICATION",
  "ISSUANCE OF STUDENT VERIFICATION",
  "ISSUANCE OF CERTIFIED TRUE COPY of TOR, Diploma and General Weighted Average for Graduate Students",
  "ISSUANCE OF TRANSCRIPT OF RECORD FOR UNDERGRADUATE STUDENT ( for TOR Employment for Undergraduate)",
  "ISSUANCE OF TRANSCRIPT OF RECORD FOR GRADUATE STUDENTS TOR Employment (for graduate/H.D/Further studies/ evaluation)",
  "ISSUANCE OF TRANSCRIPT OF RECORD FOR UNDERGRADUATE STUDENT (for TOR Evaluation / Re-Admission)",
  "ISSUANCE OF TRANSCRIPT OF RECORD FOR UNDERGRADUATE STUDENT (for TOR Honorable Dismissal)",
  "ISSUANCE OF TRANSCRIPT OF RECORD FOR Graduate Students (1st requeest)",
  "ISSUANCE OF CERTIFICATE OF GRADES",
  "ISSUANCE OF CERTIFICATE OF REGISTRATION",
];
export { sm, yrSections, yrSN, transactionsAcad, transactionsReg };
